export const storageKeys = {
  apiKey: 'aiChat_apiKey',
  apiKeyRemember: 'aiChat_apiKey_remember',
  apiKeyLastValidated: 'aiChat_apiKey_lastValidated',
  modelProvider: 'modelProvider',
  defaultModel: 'defaultModel',
  baseURL: 'baseURL',
  sttProvider: 'sttProvider',
  localWhisperModel: 'localWhisperModel',
  sttLanguage: 'sttLanguage',
  ttsProvider: 'ttsProvider',
  edgeTtsVoice: 'edgeTtsVoice',
  edgeTtsRate: 'edgeTtsRate',
  edgeTtsPitch: 'edgeTtsPitch',
  edgeTtsVolume: 'edgeTtsVolume',
  edgeTtsEmotionEnabled: 'edgeTtsEmotionEnabled',
  edgeTtsEmotionStyle: 'edgeTtsEmotionStyle',
  elevenLabsApiKey: 'elevenLabsApiKey',
  elevenLabsVoiceId: 'elevenLabsVoiceId',
  elevenLabsModelId: 'elevenLabsModelId',
  elevenLabsStability: 'elevenLabsStability',
  elevenLabsSimilarityBoost: 'elevenLabsSimilarityBoost',
  elevenLabsStyle: 'elevenLabsStyle',
  zhipuTtsVoice: 'zhipuTtsVoice',
  zhipuTtsSpeed: 'zhipuTtsSpeed',
  zhipuTtsVolume: 'zhipuTtsVolume',
  zhipuTtsEmotionEnabled: 'zhipuTtsEmotionEnabled',
  zhipuTtsEmotionStyle: 'zhipuTtsEmotionStyle',
  zhipuTtsEmotionGranularity: 'zhipuTtsEmotionGranularity',
  autoSpeakEnabled: 'autoSpeakEnabled',
} as const;

export const indexedDbInfo = {
  name: 'aiChatDB',
  stores: ['characters', 'conversations', 'messages'],
} as const;
